### ISSUE TITLE
Better Loading Screen Handling

### ISSUE THREAD

**Issue by pacas00** [pacas00/ModdersGearbox#9]
Need to handle loading better,

Currently, we block everything including UI updates.

Proposed new handling,

Postfix on someones .ctor
- Setup vars we need
- Make sure we are ready to run our own update method

Prefix on someones UnityUpdate()
- If we are not running, start up and return
- If we are running return until we are ready
- If we are ready, stop returning.

Our Update Method
- Needs to update the UI
- Or at the least, not block

**Comment by pacas00** [comment]
New Plan,

Prefix ModManager.HandleActivation

if (WorldLoadState.State != WorldLoadStateEnum.LoadModUnityData) leave prefix

if (WorldLoadState.State == WorldLoadStateEnum.LoadModUnityData) then

Check if we are ready, if not, call our own update method for loading and return
If we are ready, then leave prefix allowing normal execution

**Comment by pacas00** [comment]
Prefix LoadingControl.Update

if (WorldLoadState.State != WorldLoadStateEnum.LoadModUnityData) leave prefix

if (WorldLoadState.State == WorldLoadStateEnum.LoadModUnityData) then
- if we are ready, leave prefix	
- Set our loading text string as needed

`this.LoadingLabel.text = PersistentSettings.GetString("Game_Loading") + "[" + text + "]";`

**Comment by pacas00** [comment]
Thinking about this, We cannot patch a method we are running.

Not happening any time soon.

**Comment by pacas00** [comment]
Closing this until i think of another way to do this.

**Comment by ph3rr3t** [comment]
Can't set it up as one of those; "Must restart program to apply setting change," options you see in plenty of other programs, games, etc?
